### ISSUE TITLE
undocumented commands (hyphenation tolerance)

### ISSUE THREAD

**Issue by juh2** [ousia/from-pandoc-to-context#4]
As I encountered hyphenation issues I tried to understand hyphenation setup

The problem is that these commands are not documented.

```
\setuphyphenation
    [method=traditional]

\sethyphenationfeatures
    [strict]
```

I googled but found no real help. From my findings I guess that people know what these commands are doing and they probably know the options I was looking for. But they are badly documented.

**This is not a fault of from-pandoc-to-context**, but maybe you could document the environments so that people get an idea how to tweak the layout. This is of course a bad solution. It would be better to have a good online documentation of ConTeXt.

What I was looking for: Can I do something like this:

```
\setuphyphenation
    [method=modern]

\sethyphenationfeatures
    [tolerant]
```

**Comment by ousia** [comment]
@juh2, this feature is rather a new one.

```
\setuphyphenation
    [method=modern]
```

Would you select `modern` because you want _die neue Rechtschreibung_?

Sorry, but this is totally unrelated. It doesn’t refer to German hyphenation, but to the hyphenation method in general. (And `modern` doesn’t seem to be a valid value.)

```
\sethyphenationfeatures
    [tolerant]
```

I would be surprised if this would change anything. Although I haven’t checked it.

The command you want may be: `\setuptolerance[tolerant]`. Other possible values are: `verystrict`, `strict` and `verytolerant`.

**Comment by juh2** [comment]
Undocumented features are broken features. ;-)

This is the fault of the ConTeXt developers. They don't write documentation. 

But I solved my hyphenation problems. 
With this definition I have no Overfull lines:

```
\setupalign
[hanging, hz, tolerant]
```

**Comment by ousia** [comment]
Great, when that worked for you, @juh2.

I’m not sure whether German is more problematic to be hyphenated than English or Spanish.

I would say it is, since the German average vowel is longer than the Spanish one (at least).
